<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $comments = array(
        [          
            'from_user_id' => 1,
            'to_user_id' => 2,
            'content' => 'Comment 1',
            'coment_create_time' => '2022-01-01',
            'coment_update_time' => '2022-01-02',
            'coment_delete_time' => '2022-01-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 2,
            'to_user_id' => 3,
            'content' => 'Comment 2',
            'coment_create_time' => '2022-02-01',
            'coment_update_time' => '2022-02-02',
            'coment_delete_time' => '2022-02-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 3,
            'to_user_id' => 4,
            'content' => 'Comment 3',
            'coment_create_time' => '2022-03-01',
            'coment_update_time' => '2022-03-02',
            'coment_delete_time' => '2022-03-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 4,
            'to_user_id' => 5,
            'content' => 'Comment 4',
            'coment_create_time' => '2022-04-01',
            'coment_update_time' => '2022-04-02',
            'coment_delete_time' => '2022-04-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 5,
            'to_user_id' => 6,
            'content' => 'Comment 5',
            'coment_create_time' => '2022-05-01',
            'coment_update_time' => '2022-05-02',
            'coment_delete_time' => '2022-05-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 6,
            'to_user_id' => 7,
            'content' => 'Comment 6',
            'coment_create_time' => '2022-06-01',
            'coment_update_time' => '2022-06-02',
            'coment_delete_time' => '2022-06-03',
            'is_delete' => false,
        ],
        [          
            'from_user_id' => 1,
            'to_user_id' => 2,
            'content' => 'Comment 1',
            'coment_create_time' => '2022-01-01',
            'coment_update_time' => '2022-01-02',
            'coment_delete_time' => '2022-01-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 2,
            'to_user_id' => 3,
            'content' => 'Comment 2',
            'coment_create_time' => '2022-02-01',
            'coment_update_time' => '2022-02-02',
            'coment_delete_time' => '2022-02-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 3,
            'to_user_id' => 4,
            'content' => 'Comment 3',
            'coment_create_time' => '2022-03-01',
            'coment_update_time' => '2022-03-02',
            'coment_delete_time' => '2022-03-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 4,
            'to_user_id' => 5,
            'content' => 'Comment 4',
            'coment_create_time' => '2022-04-01',
            'coment_update_time' => '2022-04-02',
            'coment_delete_time' => '2022-04-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 5,
            'to_user_id' => 6,
            'content' => 'Comment 5',
            'coment_create_time' => '2022-05-01',
            'coment_update_time' => '2022-05-02',
            'coment_delete_time' => '2022-05-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 6,
            'to_user_id' => 7,
            'content' => 'Comment 6',
            'coment_create_time' => '2022-06-01',
            'coment_update_time' => '2022-06-02',
            'coment_delete_time' => '2022-06-03',
            'is_delete' => false,
        ],
        [          
            'from_user_id' => 1,
            'to_user_id' => 2,
            'content' => 'Comment 1',
            'coment_create_time' => '2022-01-01',
            'coment_update_time' => '2022-01-02',
            'coment_delete_time' => '2022-01-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 2,
            'to_user_id' => 3,
            'content' => 'Comment 2',
            'coment_create_time' => '2022-02-01',
            'coment_update_time' => '2022-02-02',
            'coment_delete_time' => '2022-02-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 3,
            'to_user_id' => 4,
            'content' => 'Comment 3',
            'coment_create_time' => '2022-03-01',
            'coment_update_time' => '2022-03-02',
            'coment_delete_time' => '2022-03-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 4,
            'to_user_id' => 5,
            'content' => 'Comment 4',
            'coment_create_time' => '2022-04-01',
            'coment_update_time' => '2022-04-02',
            'coment_delete_time' => '2022-04-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 5,
            'to_user_id' => 6,
            'content' => 'Comment 5',
            'coment_create_time' => '2022-05-01',
            'coment_update_time' => '2022-05-02',
            'coment_delete_time' => '2022-05-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 6,
            'to_user_id' => 7,
            'content' => 'Comment 6',
            'coment_create_time' => '2022-06-01',
            'coment_update_time' => '2022-06-02',
            'coment_delete_time' => '2022-06-03',
            'is_delete' => false,
        ],
        [          
            'from_user_id' => 1,
            'to_user_id' => 2,
            'content' => 'Comment 1',
            'coment_create_time' => '2022-01-01',
            'coment_update_time' => '2022-01-02',
            'coment_delete_time' => '2022-01-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 2,
            'to_user_id' => 3,
            'content' => 'Comment 2',
            'coment_create_time' => '2022-02-01',
            'coment_update_time' => '2022-02-02',
            'coment_delete_time' => '2022-02-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 3,
            'to_user_id' => 4,
            'content' => 'Comment 3',
            'coment_create_time' => '2022-03-01',
            'coment_update_time' => '2022-03-02',
            'coment_delete_time' => '2022-03-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 4,
            'to_user_id' => 5,
            'content' => 'Comment 4',
            'coment_create_time' => '2022-04-01',
            'coment_update_time' => '2022-04-02',
            'coment_delete_time' => '2022-04-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 5,
            'to_user_id' => 6,
            'content' => 'Comment 5',
            'coment_create_time' => '2022-05-01',
            'coment_update_time' => '2022-05-02',
            'coment_delete_time' => '2022-05-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 6,
            'to_user_id' => 7,
            'content' => 'Comment 6',
            'coment_create_time' => '2022-06-01',
            'coment_update_time' => '2022-06-02',
            'coment_delete_time' => '2022-06-03',
            'is_delete' => false,
        ],
        [          
            'from_user_id' => 1,
            'to_user_id' => 2,
            'content' => 'Comment 1',
            'coment_create_time' => '2022-01-01',
            'coment_update_time' => '2022-01-02',
            'coment_delete_time' => '2022-01-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 2,
            'to_user_id' => 3,
            'content' => 'Comment 2',
            'coment_create_time' => '2022-02-01',
            'coment_update_time' => '2022-02-02',
            'coment_delete_time' => '2022-02-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 3,
            'to_user_id' => 4,
            'content' => 'Comment 3',
            'coment_create_time' => '2022-03-01',
            'coment_update_time' => '2022-03-02',
            'coment_delete_time' => '2022-03-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 4,
            'to_user_id' => 5,
            'content' => 'Comment 4',
            'coment_create_time' => '2022-04-01',
            'coment_update_time' => '2022-04-02',
            'coment_delete_time' => '2022-04-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 5,
            'to_user_id' => 6,
            'content' => 'Comment 5',
            'coment_create_time' => '2022-05-01',
            'coment_update_time' => '2022-05-02',
            'coment_delete_time' => '2022-05-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 6,
            'to_user_id' => 7,
            'content' => 'Comment 6',
            'coment_create_time' => '2022-06-01',
            'coment_update_time' => '2022-06-02',
            'coment_delete_time' => '2022-06-03',
            'is_delete' => false,
        ],
        [          
            'from_user_id' => 1,
            'to_user_id' => 2,
            'content' => 'Comment 1',
            'coment_create_time' => '2022-01-01',
            'coment_update_time' => '2022-01-02',
            'coment_delete_time' => '2022-01-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 2,
            'to_user_id' => 3,
            'content' => 'Comment 2',
            'coment_create_time' => '2022-02-01',
            'coment_update_time' => '2022-02-02',
            'coment_delete_time' => '2022-02-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 3,
            'to_user_id' => 4,
            'content' => 'Comment 3',
            'coment_create_time' => '2022-03-01',
            'coment_update_time' => '2022-03-02',
            'coment_delete_time' => '2022-03-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 4,
            'to_user_id' => 5,
            'content' => 'Comment 4',
            'coment_create_time' => '2022-04-01',
            'coment_update_time' => '2022-04-02',
            'coment_delete_time' => '2022-04-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 5,
            'to_user_id' => 6,
            'content' => 'Comment 5',
            'coment_create_time' => '2022-05-01',
            'coment_update_time' => '2022-05-02',
            'coment_delete_time' => '2022-05-03',
            'is_delete' => false,
        ],
        [
            'from_user_id' => 6,
            'to_user_id' => 7,
            'content' => 'Comment 6',
            'coment_create_time' => '2022-06-01',
            'coment_update_time' => '2022-06-02',
            'coment_delete_time' => '2022-06-03',
            'is_delete' => false,
        ]
       );
       
        
        DB::table('comments')->delete();
        DB::table('comments')->insert($comments);
    }
}
